### ISSUE TITLE
The written voxel GRO file is not aligned (scaled) with the atomgroup

### ISSUE THREAD

**Issue by BartBruininks** [BartBruininks/mdvcontainment#10]
It would be super nice if the voxel grid GRO files and the molecular structure files would be super imposable.

**Comment by diegomasone** [comment]
Indeed! That would be very useful for visualization. :)

**Comment by BartBruininks** [comment]
It appears this was already a feature that was more or less supported as one could give a scaling factor. To make this more easier we now also support giving a universe to the voxels_to_gro function, which autoscales to make the voxel grid match the dimensions of the input point cloud.
